import { Container } from "@/components/layout/container";
import { Section } from "@/components/layout/section";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";

const featuredGuides = ["A practical first security checklist", "How to spot phishing before it costs you", "Getting passwords and MFA right"];
const securityAreas = [["Email & Phishing", "Recognize risky messages and protect business inboxes."], ["Passwords & MFA", "Build simple habits that make account takeovers harder."], ["Website Security", "Cover the essentials that keep your online presence dependable."], ["Devices & Networks", "Secure the everyday equipment your team relies on."], ["Backups & Recovery", "Prepare for mistakes, outages, and ransomware before they happen."]];

export default function Home() {
  return <div id="top" className="flex min-h-svh flex-col"><SiteHeader /><main className="flex-1">
    <Section className="py-20 sm:py-28"><Container><div className="max-w-3xl"><Badge>Cybersecurity for small businesses</Badge><h1 className="mt-5 text-4xl font-bold tracking-tight text-foreground sm:text-5xl lg:text-6xl">Practical cybersecurity for small businesses without a security team.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">Simple, actionable security guidance for businesses that do not have a dedicated security team.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button href="#start-here">Start With the Basics</Button><Button href="#guides" variant="secondary">Explore Guides</Button></div></div></Container></Section>
    <Section className="border-y border-border bg-surface-muted"><Container><div className="grid gap-8 md:grid-cols-3">{[["Practical guidance", "Clear next steps that fit real teams and real schedules."], ["No jargon", "Beginner-friendly explanations without talking down to you."], ["Useful decisions", "Security checklists and tool evaluations you can act on."]].map(([title, copy]) => <div key={title}><h2 className="text-lg font-semibold text-foreground">{title}</h2><p className="mt-2 leading-7 text-muted-foreground">{copy}</p></div>)}</div></Container></Section>
    <Section id="guides"><Container><div className="max-w-2xl"><p className="text-sm font-semibold uppercase tracking-wider text-primary">Featured guides</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-foreground">Start with the security work that matters most.</h2></div><div className="mt-8 grid gap-5 md:grid-cols-3">{featuredGuides.map((title, index) => <Card key={title}><p className="text-sm font-medium text-primary">Guide {index + 1}</p><h3 className="mt-4 text-xl font-semibold text-foreground">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">A future practical guide for small-business teams.</p></Card>)}</div></Container></Section>
    <Section id="small-business" className="bg-surface-muted"><Container><div className="max-w-2xl"><p className="text-sm font-semibold uppercase tracking-wider text-primary">Small business security</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-foreground">Build confidence across the essentials.</h2></div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{securityAreas.map(([title, copy]) => <Card key={title} className="bg-background"><h3 className="text-lg font-semibold text-foreground">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{copy}</p></Card>)}</div></Container></Section>
    <Section id="start-here"><Container><div className="grid gap-8 rounded-lg border border-border bg-surface p-8 md:grid-cols-[1.3fr_1fr] md:items-center md:p-10"><div><p className="text-sm font-semibold uppercase tracking-wider text-primary">New to cybersecurity?</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-foreground">Start with the basics, not the buzzwords.</h2></div><p className="leading-7 text-muted-foreground">We will help you understand the highest-impact steps first, so you can make steady progress without becoming a security expert.</p></div></Container></Section>
    <Section id="tools" className="bg-surface-muted"><Container><div className="max-w-2xl"><p className="text-sm font-semibold uppercase tracking-wider text-primary">Tools</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-foreground">Straightforward tool reviews, when you need them.</h2><p className="mt-4 leading-7 text-muted-foreground">Future comparisons will focus on what a small business needs to know before choosing a security tool.</p></div></Container></Section>
    <Section><Container><div className="rounded-lg bg-primary px-6 py-10 text-primary-foreground sm:px-10"><p className="text-sm font-semibold uppercase tracking-wider">Stay informed</p><h2 className="mt-3 text-3xl font-bold tracking-tight">Practical security updates are coming.</h2><p className="mt-4 max-w-2xl leading-7 text-primary-foreground/85">A newsletter signup will be available here in a future phase.</p></div></Container></Section>
    <Section className="border-t border-border" aria-labelledby="final-cta-title"><Container className="text-center"><h2 id="final-cta-title" className="text-3xl font-bold tracking-tight text-foreground">Make your next security improvement a practical one.</h2><p className="mx-auto mt-4 max-w-xl leading-7 text-muted-foreground">Start with the fundamentals and give your business a stronger foundation.</p><Button href="#start-here" className="mt-7">Start With the Basics</Button></Container></Section>
  </main><SiteFooter /></div>;
}
