import Checklist from "@/content/guides/small-business-cybersecurity-checklist.mdx";
import MFA from "@/content/guides/mfa-for-small-businesses.mdx";
import PasswordPolicy from "@/content/guides/small-business-password-policy.mdx";
import Phishing from "@/content/guides/small-business-phishing-protection.mdx";
import BackupRansomware from "@/content/guides/small-business-backup-ransomware-protection.mdx";
import IncidentResponse from "@/content/guides/small-business-incident-response-plan.mdx";
import PasswordManagerGuide from "@/content/guides/small-business-password-manager-guide.mdx";
import BECGuide from "@/content/guides/business-email-compromise-small-business-payment-fraud.mdx";
import ComputerSecurity from "@/content/guides/small-business-computer-laptop-security.mdx";
import M365Security from "@/content/guides/microsoft-365-security-small-business.mdx";
import OffboardingChecklist from "@/content/guides/employee-offboarding-security-checklist.mdx";
import WifiSecurity from "@/content/guides/small-business-wifi-network-security.mdx";
import DomainSecurity from "@/content/guides/small-business-domain-name-security.mdx";
import { contentPillars, type Article, type ArticleCategory } from "@/types/content";

const articles: Article[] = [
  { title: "Small Business Cybersecurity Checklist: 25 Things to Secure Your Business", description: "A practical 25-point checklist to help small businesses protect accounts, email, devices, data, backups, and incident response.", slug: "small-business-cybersecurity-checklist", category: "security-management", tags: ["small-business", "cybersecurity-checklist", "security-basics", "risk-management", "backups", "phishing"], author: "Kapil Shah", publishedAt: "2026-08-15", updatedAt: "2026-09-16", readingTime: 15, featured: true, draft: false, difficulty: "beginner", businessRelevance: "high", beginnerFriendly: true, relatedSlugs: ["mfa-for-small-businesses", "small-business-computer-laptop-security", "microsoft-365-security-small-business"], Content: Checklist },
  { title: "Multi-Factor Authentication (MFA) for Small Businesses: A Practical Guide", description: "A practical beginner-friendly guide to choosing, rolling out, and recovering multi-factor authentication for critical small-business accounts.", slug: "mfa-for-small-businesses", category: "account-identity", tags: ["mfa", "accounts", "security-basics", "small-business", "email-security", "security-management"], author: "Kapil Shah", publishedAt: "2026-08-15", updatedAt: "2026-09-16", readingTime: 12, featured: true, draft: false, difficulty: "beginner", businessRelevance: "essential", beginnerFriendly: true, relatedSlugs: ["small-business-cybersecurity-checklist", "microsoft-365-security-small-business", "small-business-phishing-protection"], Content: MFA },
  { title: "How to Create a Strong Password Policy for a Small Business", description: "A practical password-policy guide for small businesses covering long unique passwords, password managers, MFA, access removal, and compromise response.", slug: "small-business-password-policy", category: "account-identity", tags: ["passwords", "password-policy", "account-security", "mfa", "small-business", "security-management"], author: "Kapil Shah", publishedAt: "2026-09-16", readingTime: 15, featured: true, draft: false, difficulty: "beginner", businessRelevance: "essential", beginnerFriendly: true, relatedSlugs: ["small-business-password-manager-guide", "employee-offboarding-security-checklist", "small-business-cybersecurity-checklist"], Content: PasswordPolicy },
  { title: "Small Business Phishing Protection: How to Spot and Stop Email Scams", description: "A practical guide for small businesses to recognize phishing, verify suspicious requests, and respond safely to email scams.", slug: "small-business-phishing-protection", category: "email-phishing", tags: ["phishing", "email-security", "small-business", "business-email-compromise", "account-security", "incident-response"], author: "Kapil Shah", publishedAt: "2026-08-15", updatedAt: "2026-09-16", readingTime: 11, featured: true, draft: false, difficulty: "beginner", businessRelevance: "high", beginnerFriendly: true, relatedSlugs: ["business-email-compromise-small-business-payment-fraud", "microsoft-365-security-small-business", "small-business-cybersecurity-checklist"], Content: Phishing },
  { title: "Small Business Backup and Ransomware Protection: A Practical Recovery Plan", seoTitle: "Small Business Backup and Ransomware Protection", description: "Plan recoverable backups for a small business: choose critical data, protect backup access, test restores, and prepare for ransomware safely.", slug: "small-business-backup-ransomware-protection", category: "data-recovery", tags: ["backups", "ransomware", "data-recovery", "small-business", "incident-response"], author: "Kapil Shah", publishedAt: "2026-09-27", readingTime: 7, featured: false, draft: false, difficulty: "beginner", businessRelevance: "essential", beginnerFriendly: true, relatedSlugs: ["small-business-computer-laptop-security", "small-business-cybersecurity-checklist", "small-business-incident-response-plan"], Content: BackupRansomware },
  { title: "How to Create a Small Business Cybersecurity Incident Response Plan", seoTitle: "Small Business Incident Response Plan", description: "Create a practical incident response plan for a small business, with reporting steps, offline contacts, recovery priorities, and a simple practice exercise.", slug: "small-business-incident-response-plan", category: "incident-response", tags: ["incident-response", "small-business", "recovery", "phishing", "account-security"], author: "Kapil Shah", publishedAt: "2026-09-27", readingTime: 8, featured: false, draft: false, difficulty: "beginner", businessRelevance: "essential", beginnerFriendly: true, relatedSlugs: ["business-email-compromise-small-business-payment-fraud", "employee-offboarding-security-checklist", "small-business-cybersecurity-checklist"], Content: IncidentResponse },
  { title: "Small Business Password Manager Guide: How to Store Business Passwords Safely", seoTitle: "Small Business Password Manager Guide", description: "Learn how a small business can store passwords safely, manage shared access and recovery, and onboard or offboard employees with a password manager.", slug: "small-business-password-manager-guide", category: "account-identity", tags: ["password-manager", "passwords", "account-security", "small-business", "onboarding", "offboarding", "mfa"], author: "Kapil Shah", publishedAt: "2026-09-27", readingTime: 12, featured: false, draft: false, difficulty: "beginner", businessRelevance: "essential", beginnerFriendly: true, relatedSlugs: ["small-business-password-policy", "employee-offboarding-security-checklist", "mfa-for-small-businesses"], coverImage: { src: "/images/guides/small-business-password-manager-hero.svg", alt: "A small-business password vault keeps separate work account credentials in a protected, organized space.", width: 1200, height: 630 }, Content: PasswordManagerGuide },
  { title: "Business Email Compromise: How Small Businesses Can Prevent Payment Fraud", seoTitle: "Business Email Compromise: Small Business Payment Fraud Prevention", description: "Learn how small businesses can recognize business email compromise (BEC), stop changed bank details and fake invoice scams, and verify payment requests safely.", slug: "business-email-compromise-small-business-payment-fraud", category: "email-phishing", tags: ["business-email-compromise", "bec", "payment-fraud", "email-security", "small-business", "phishing", "fraud-prevention", "incident-response"], author: "Kapil Shah", publishedAt: "2026-09-30", readingTime: 14, featured: false, draft: false, difficulty: "beginner", businessRelevance: "essential", beginnerFriendly: true, relatedSlugs: ["microsoft-365-security-small-business", "small-business-phishing-protection", "small-business-incident-response-plan"], coverImage: { src: "/images/guides/small-business-bec-payment-fraud-hero.jpg", alt: "A small-business payment workflow being targeted by a fraudulent email request, showing the verification checkpoint that prevents payment fraud.", width: 1920, height: 1080 }, Content: BECGuide },
  { title: "Small Business Work Computer Security: How to Protect Laptops and Workstations", seoTitle: "Small Business Laptop and Work Computer Security Guide", description: "A practical guide to securing small business laptops and workstations: BitLocker, FileVault, least privilege, patching, antivirus, and theft response.", slug: "small-business-computer-laptop-security", category: "website-device", tags: ["device-security", "laptops", "encryption", "bitlocker", "endpoint-security", "small-business", "security-basics"], author: "Kapil Shah", publishedAt: "2026-09-30", readingTime: 14, featured: false, draft: false, difficulty: "beginner", businessRelevance: "essential", beginnerFriendly: true, relatedSlugs: ["small-business-cybersecurity-checklist", "small-business-wifi-network-security", "mfa-for-small-businesses"], coverImage: { src: "/images/guides/small-business-laptop-security-baseline.svg", alt: "Six essential workstation security controls for small businesses: full-disk encryption, standard user accounts, automated updates, screen locks, endpoint antivirus hygiene, and loss containment plans.", width: 1200, height: 580 }, Content: ComputerSecurity },
  { title: "Microsoft 365 Security for Small Businesses: Essential Settings to Protect Your Tenant", seoTitle: "Microsoft 365 Security for Small Businesses: Tenant Hardening", description: "Practical Microsoft 365 security settings for small businesses: Security Defaults, dedicated admin accounts, disabling auto-forwarding, app consent, and audit logs.", slug: "microsoft-365-security-small-business", category: "account-identity", tags: ["microsoft-365", "email-security", "mfa", "business-email-compromise", "entra-id", "small-business", "cloud-security"], author: "Kapil Shah", publishedAt: "2026-09-30", readingTime: 16, featured: false, draft: false, difficulty: "beginner", businessRelevance: "essential", beginnerFriendly: true, relatedSlugs: ["business-email-compromise-small-business-payment-fraud", "small-business-domain-name-security", "employee-offboarding-security-checklist"], coverImage: { src: "/images/guides/microsoft-365-security-baseline.svg", alt: "Six core Microsoft 365 security baseline stages: Identity & MFA, Mailbox protection, File sharing restrictions, App consent controls, Audit logging, and Emergency break-glass recovery.", width: 1200, height: 560 }, Content: M365Security },
  { title: "Employee Offboarding Security Checklist: How to Revoke Access When Staff Leave", seoTitle: "Employee Offboarding Security Checklist for Small Businesses", description: "A step-by-step security checklist for small businesses to revoke access, recover hardware, audit mailboxes, and prevent data leakage when employees leave.", slug: "employee-offboarding-security-checklist", category: "security-management", tags: ["offboarding", "access-management", "password-manager", "microsoft-365", "identity", "small-business", "risk-management"], author: "Kapil Shah", publishedAt: "2026-09-30", readingTime: 13, featured: false, draft: false, difficulty: "beginner", businessRelevance: "essential", beginnerFriendly: true, relatedSlugs: ["microsoft-365-security-small-business", "small-business-password-manager-guide", "small-business-cybersecurity-checklist"], coverImage: { src: "/images/guides/employee-offboarding-security-workflow.svg", alt: "Four-phase employee offboarding security workflow: Pre-departure inventory, final-day access cutover, post-departure auditing and secrets rotation, and archival license management.", width: 1200, height: 540 }, Content: OffboardingChecklist },
  { title: "Small Business Wi-Fi Security: How to Protect Your Office Wireless Network", seoTitle: "Small Business Wi-Fi and Office Network Security Guide", description: "Learn how small businesses can secure office Wi-Fi networks: separate guest Wi-Fi, change default router passwords, enable WPA3, isolate IoT devices, and update firmware.", slug: "small-business-wifi-network-security", category: "website-device", tags: ["wifi-security", "network-security", "router-hardening", "wpa3", "guest-network", "small-business", "iot-security"], author: "Kapil Shah", publishedAt: "2026-09-30", readingTime: 13, featured: false, draft: false, difficulty: "beginner", businessRelevance: "essential", beginnerFriendly: true, relatedSlugs: ["small-business-computer-laptop-security", "small-business-cybersecurity-checklist", "small-business-password-manager-guide"], coverImage: { src: "/images/guides/small-business-wifi-network-segmentation.svg", alt: "Small business office Wi-Fi network segmentation diagram showing separation between primary corporate workstations, isolated guest devices, and untrusted IoT hardware.", width: 1200, height: 560 }, Content: WifiSecurity },
  { title: "Domain Name Security for Small Businesses: How to Prevent Domain Takeovers and DNS Hijacking", seoTitle: "Small Business Domain Security and Takeover Prevention Guide", description: "Protect your small business domain name from theft and DNS hijacking: enable registrar locks, enforce MFA on registrar accounts, prevent expiration, and secure DNS records.", slug: "small-business-domain-name-security", category: "website-device", tags: ["domain-security", "dns", "dnssec", "domain-takeover", "registrar-lock", "small-business", "brand-protection"], author: "Kapil Shah", publishedAt: "2026-09-30", readingTime: 14, featured: false, draft: false, difficulty: "beginner", businessRelevance: "essential", beginnerFriendly: true, relatedSlugs: ["business-email-compromise-small-business-payment-fraud", "microsoft-365-security-small-business", "small-business-cybersecurity-checklist"], coverImage: { src: "/images/guides/small-business-domain-security-layers.svg", alt: "Four defensive layers of small business domain security: Registrar account protection, transfer locks and auto-renewal, DNS record integrity and DNSSEC, and legal corporate ownership governance.", width: 1200, height: 560 }, Content: DomainSecurity },
];

export function getAllArticles() { return articles.filter((article) => !article.draft); }
export function getArticleBySlug(slug: string) { return getAllArticles().find((article) => article.slug === slug); }
export function getArticlesByCategory(category: ArticleCategory) { return getAllArticles().filter((article) => article.category === category); }
export function getArticlesByTag(tag: string) { return getAllArticles().filter((article) => article.tags.includes(tag)); }
export function getFeaturedArticles() { return getAllArticles().filter((article) => article.featured); }
export function getPillar(category: ArticleCategory) { return contentPillars.find((pillar) => pillar.value === category)!; }
export function getRelatedArticles(article: Article, limit = 3) { const published = getAllArticles().filter((candidate) => candidate.slug !== article.slug); const explicit = (article.relatedSlugs ?? []).map((slug) => published.find((candidate) => candidate.slug === slug)).filter((candidate): candidate is Article => Boolean(candidate)); const remaining = published.filter((candidate) => !explicit.some(({ slug }) => slug === candidate.slug)).map((candidate) => ({ candidate, score: (candidate.category === article.category ? 2 : 0) + candidate.tags.filter((tag) => article.tags.includes(tag)).length })).filter(({ score }) => score > 0).sort((a, b) => b.score - a.score).map(({ candidate }) => candidate); return [...explicit, ...remaining].slice(0, limit); }
