import Checklist from "@/content/guides/small-business-cybersecurity-checklist.mdx";
import MFA from "@/content/guides/mfa-for-small-businesses.mdx";
import PasswordPolicy from "@/content/guides/small-business-password-policy.mdx";
import Phishing from "@/content/guides/small-business-phishing-protection.mdx";
import BackupRansomware from "@/content/guides/small-business-backup-ransomware-protection.mdx";
import IncidentResponse from "@/content/guides/small-business-incident-response-plan.mdx";
import PasswordManagerGuide from "@/content/guides/small-business-password-manager-guide.mdx";
import BECGuide from "@/content/guides/business-email-compromise-small-business-payment-fraud.mdx";
import { contentPillars, type Article, type ArticleCategory } from "@/types/content";

const articles: Article[] = [
  { title: "Small Business Cybersecurity Checklist: 25 Things to Secure Your Business", description: "A practical 25-point checklist to help small businesses protect accounts, email, devices, data, backups, and incident response.", slug: "small-business-cybersecurity-checklist", category: "security-management", tags: ["small-business", "cybersecurity-checklist", "security-basics", "risk-management", "backups", "phishing"], author: "Kapil Shah", publishedAt: "2026-08-15", updatedAt: "2026-09-16", readingTime: 15, featured: true, draft: false, difficulty: "beginner", businessRelevance: "high", beginnerFriendly: true, relatedSlugs: ["mfa-for-small-businesses", "small-business-phishing-protection"], Content: Checklist },
  { title: "Multi-Factor Authentication (MFA) for Small Businesses: A Practical Guide", description: "A practical beginner-friendly guide to choosing, rolling out, and recovering multi-factor authentication for critical small-business accounts.", slug: "mfa-for-small-businesses", category: "account-identity", tags: ["mfa", "accounts", "security-basics", "small-business", "email-security", "security-management"], author: "Kapil Shah", publishedAt: "2026-08-15", updatedAt: "2026-09-16", readingTime: 12, featured: true, draft: false, difficulty: "beginner", businessRelevance: "essential", beginnerFriendly: true, relatedSlugs: ["small-business-cybersecurity-checklist", "small-business-phishing-protection"], Content: MFA },
  { title: "How to Create a Strong Password Policy for a Small Business", description: "A practical password-policy guide for small businesses covering long unique passwords, password managers, MFA, access removal, and compromise response.", slug: "small-business-password-policy", category: "account-identity", tags: ["passwords", "password-policy", "account-security", "mfa", "small-business", "security-management"], author: "Kapil Shah", publishedAt: "2026-09-16", readingTime: 15, featured: true, draft: false, difficulty: "beginner", businessRelevance: "essential", beginnerFriendly: true, relatedSlugs: ["mfa-for-small-businesses", "small-business-cybersecurity-checklist", "small-business-phishing-protection"], Content: PasswordPolicy },
  { title: "Small Business Phishing Protection: How to Spot and Stop Email Scams", description: "A practical guide for small businesses to recognize phishing, verify suspicious requests, and respond safely to email scams.", slug: "small-business-phishing-protection", category: "email-phishing", tags: ["phishing", "email-security", "small-business", "business-email-compromise", "account-security", "incident-response"], author: "Kapil Shah", publishedAt: "2026-08-15", updatedAt: "2026-09-16", readingTime: 11, featured: true, draft: false, difficulty: "beginner", businessRelevance: "high", beginnerFriendly: true, relatedSlugs: ["business-email-compromise-small-business-payment-fraud", "small-business-cybersecurity-checklist", "mfa-for-small-businesses"], Content: Phishing },
  { title: "Small Business Backup and Ransomware Protection: A Practical Recovery Plan", seoTitle: "Small Business Backup and Ransomware Protection", description: "Plan recoverable backups for a small business: choose critical data, protect backup access, test restores, and prepare for ransomware safely.", slug: "small-business-backup-ransomware-protection", category: "data-recovery", tags: ["backups", "ransomware", "data-recovery", "small-business", "incident-response"], author: "Kapil Shah", publishedAt: "2026-09-27", readingTime: 7, featured: false, draft: false, difficulty: "beginner", businessRelevance: "essential", beginnerFriendly: true, relatedSlugs: ["small-business-cybersecurity-checklist", "small-business-incident-response-plan"], Content: BackupRansomware },
  { title: "How to Create a Small Business Cybersecurity Incident Response Plan", seoTitle: "Small Business Incident Response Plan", description: "Create a practical incident response plan for a small business, with reporting steps, offline contacts, recovery priorities, and a simple practice exercise.", slug: "small-business-incident-response-plan", category: "incident-response", tags: ["incident-response", "small-business", "recovery", "phishing", "account-security"], author: "Kapil Shah", publishedAt: "2026-09-27", readingTime: 8, featured: false, draft: false, difficulty: "beginner", businessRelevance: "essential", beginnerFriendly: true, relatedSlugs: ["business-email-compromise-small-business-payment-fraud", "small-business-cybersecurity-checklist", "small-business-backup-ransomware-protection"], Content: IncidentResponse },
  { title: "Small Business Password Manager Guide: How to Store Business Passwords Safely", seoTitle: "Small Business Password Manager Guide", description: "Learn how a small business can store passwords safely, manage shared access and recovery, and onboard or offboard employees with a password manager.", slug: "small-business-password-manager-guide", category: "account-identity", tags: ["password-manager", "passwords", "account-security", "small-business", "onboarding", "offboarding", "mfa"], author: "Kapil Shah", publishedAt: "2026-09-27", readingTime: 12, featured: false, draft: false, difficulty: "beginner", businessRelevance: "essential", beginnerFriendly: true, relatedSlugs: ["small-business-password-policy", "mfa-for-small-businesses", "small-business-cybersecurity-checklist"], coverImage: { src: "/images/guides/small-business-password-manager-hero.svg", alt: "A small-business password vault keeps separate work account credentials in a protected, organized space.", width: 1200, height: 630 }, Content: PasswordManagerGuide },
  { title: "Business Email Compromise: How Small Businesses Can Prevent Payment Fraud", seoTitle: "Business Email Compromise: Small Business Payment Fraud Prevention", description: "Learn how small businesses can recognize business email compromise (BEC), stop changed bank details and fake invoice scams, and verify payment requests safely.", slug: "business-email-compromise-small-business-payment-fraud", category: "email-phishing", tags: ["business-email-compromise", "bec", "payment-fraud", "email-security", "small-business", "phishing", "fraud-prevention", "incident-response"], author: "Kapil Shah", publishedAt: "2026-09-30", readingTime: 14, featured: false, draft: false, difficulty: "beginner", businessRelevance: "essential", beginnerFriendly: true, relatedSlugs: ["small-business-phishing-protection", "small-business-incident-response-plan", "mfa-for-small-businesses"], coverImage: { src: "/images/guides/small-business-bec-payment-fraud-hero.jpg", alt: "A small-business payment workflow being targeted by a fraudulent email request, showing the verification checkpoint that prevents payment fraud.", width: 1920, height: 1080 }, Content: BECGuide },
];

export function getAllArticles() { return articles.filter((article) => !article.draft); }
export function getArticleBySlug(slug: string) { return getAllArticles().find((article) => article.slug === slug); }
export function getArticlesByCategory(category: ArticleCategory) { return getAllArticles().filter((article) => article.category === category); }
export function getArticlesByTag(tag: string) { return getAllArticles().filter((article) => article.tags.includes(tag)); }
export function getFeaturedArticles() { return getAllArticles().filter((article) => article.featured); }
export function getPillar(category: ArticleCategory) { return contentPillars.find((pillar) => pillar.value === category)!; }
export function getRelatedArticles(article: Article, limit = 3) { const published = getAllArticles().filter((candidate) => candidate.slug !== article.slug); const explicit = (article.relatedSlugs ?? []).map((slug) => published.find((candidate) => candidate.slug === slug)).filter((candidate): candidate is Article => Boolean(candidate)); const remaining = published.filter((candidate) => !explicit.some(({ slug }) => slug === candidate.slug)).map((candidate) => ({ candidate, score: (candidate.category === article.category ? 2 : 0) + candidate.tags.filter((tag) => article.tags.includes(tag)).length })).filter(({ score }) => score > 0).sort((a, b) => b.score - a.score).map(({ candidate }) => candidate); return [...explicit, ...remaining].slice(0, limit); }
