import type { Metadata } from "next";
import { ArticleCard } from "@/components/content/article-card";
import { Container } from "@/components/layout/container";
import { Section } from "@/components/layout/section";
import { getAllArticles } from "@/lib/content";
import { contentPillars } from "@/types/content";

export const metadata: Metadata = { title: "Cybersecurity Guides", description: "Practical cybersecurity guides for small businesses without a dedicated security team.", alternates: { canonical: "/guides" } };
export default function GuidesPage() { const articles = getAllArticles(); const featured = articles.filter((article) => article.featured); return <main><Section><Container><header className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-wider text-primary">Cybersecurity guides</p><h1 className="mt-3 text-4xl font-bold tracking-tight text-foreground sm:text-5xl">Practical security guidance for the work that matters.</h1><p className="mt-5 text-lg leading-8 text-muted-foreground">Guides are organized around six security pillars for businesses without a dedicated security team.</p></header><nav className="mt-10" aria-label="Security pillars"><ul className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{contentPillars.map((pillar) => <li key={pillar.value}><a href={`#${pillar.value}`} className="block rounded-lg border border-border bg-surface p-4 hover:bg-surface-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><p className="font-semibold text-foreground">{pillar.label}</p><p className="mt-1 text-sm leading-6 text-muted-foreground">{pillar.description}</p></a></li>)}</ul></nav>{featured.length ? <section className="mt-14" aria-labelledby="featured-guides"><h2 id="featured-guides" className="text-2xl font-bold tracking-tight text-foreground">Featured guides</h2><div className="mt-6 grid gap-5 md:grid-cols-3">{featured.map((article) => <ArticleCard key={article.slug} article={article} />)}</div></section> : null}<section className="mt-14" aria-labelledby="all-guides"><h2 id="all-guides" className="text-2xl font-bold tracking-tight text-foreground">All guides by pillar</h2><div className="mt-8 space-y-12">{contentPillars.map((pillar) => { const pillarArticles = articles.filter((article) => article.category === pillar.value); return <section key={pillar.value} id={pillar.value} aria-labelledby={`${pillar.value}-title`}><h3 id={`${pillar.value}-title`} className="text-xl font-semibold text-foreground">{pillar.label}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{pillar.description}</p>{pillarArticles.length ? <div className="mt-5 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{pillarArticles.map((article) => <ArticleCard key={article.slug} article={article} />)}</div> : <p className="mt-5 text-sm text-muted-foreground">Guides for this pillar are being prepared.</p>}</section>; })}</div></section></Container></Section></main>; }
